### ISSUE TITLE
Question: how to start the after built ?

### ISSUE THREAD

**Issue by akktis** [edx/frontend-auth#37]
Hello guys,

i successfully built with webpack the project.

then i add 
"start": "NODE_ENV=production BABEL_ENV=production webpack-dev-server --config=webpack.config.js --progress",

into the script of my package.json

so i start it  and then i get this :

<img width="1680" alt="Screenshot 2019-07-17 at 19 38 21" src="https://user-images.githubusercontent.com/7902449/61397556-7289bb80-a8ca-11e9-8e51-3f6712069dae.png">

if you can help a bit with this part please 

thanks a lot

**Comment by stvstnfrd** [comment]
Hi @akktis I'm going to close this as we're archiving this repository in favor of https://github.com/edx/frontend-platform ; thanks!
