### ISSUE TITLE
Question: How about issuing multiple async requests to refresh token?

### ISSUE THREAD

**Issue by pcliupc** [edx/frontend-auth#75]
If frontend is issuing multiple api calls at the same time and jwt token is expired, multiple requests will be issued to refresh token, is there any problem in this scenario?

And how about the frontend code calls both LMS（use session authentication） and IDA's (use JWT token authentication) API?

**Comment by stvstnfrd** [comment]
Hi @pcliupc  I'm going to close this as we're archiving this repository in favor of https://github.com/edx/frontend-platform ; thanks!
